dimensions:

  time:
    existence_check: true

  diameter_classes:
    existence_check: false

  velocity_classes:
    existence_check: true

  bad_dimension:
    existence_check: true


variables:

  longitude:
    existence_check: true
    emptiness_check: true
    data_boundaries_check:
      perform_check: true
      lower_bound: 0
      upper_bound: 1

  latitude:
    existence_check: true
    emptiness_check: true
    data_boundaries_check:
      perform_check: true
      lower_bound: 0
      upper_bound: 1

  datetime:
    existence_check: true
    emptiness_check: true
    data_boundaries_check:
      perform_check: true
      lower_bound: 0
      upper_bound: 1

  bad_variable:
    existence_check: true
    emptiness_check: true
    data_boundaries_check:
      perform_check: true
      lower_bound: 0
      upper_bound: 1


global attributes:

  title:
    existence_check: true
    emptiness_check: true

  source:
    existence_check: true
    emptiness_check: true

  contributors:
    existence_check: false
    emptiness_check: true

  bad_attribute:
    existence_check: true
    emptiness_check: true
