dimensions:
  example_dimension:
    existence_check: true

variables:
  example_variable:
    existence_check: true
    emptiness_check: true
    data_boundaries_check:
      perform_check: true
      lower_bound: 0
      upper_bound: 1
    data_points_amount_check:
      perform_check: true
      minimum: 100
    adjacent_values_difference_check:
      over_which_dimension: [0]
      maximum_difference: [1]
    consecutive_identical_values_check:
      maximum: 25
    expected_dimensions_check:
      perform_check: true
      expected_dimensions: [time, velocity_classes]

global attributes:
  example_gl_attr:
    existence_check: true
    emptiness_check: true

file size:
  perform_check: true
  lower_bound: 10000
  upper_bound: 20000
