dimensions:
  example_dimension:
    does_it_exist_check: true

variables:
  raw_data:
    does_it_exist_check: true
    is_data_within_boundaries_check:
      perform_check: true
      lower_bound: 0
      upper_bound: 1
    are_there_enough_data_points_check:
      perform_check: true
      threshold: 100
    do_values_change_at_acceptable_rate_check:
      perform_check: true
      acceptable_difference: 1
    is_value_constant_for_too_long_check:
      perform_check: true
      over_which_dimensions: [0,1,2]
      threshold_for_each_dimension: [25,25,20]
    expected_dimensions_check:
      perform_check: true
      expected_dimensions: [time, velocity_classes]

global attributes:
  example_gl_attr:
    does_it_exist_check: true
    is_it_empty_check: true

file size:
  perform_check: true
  lower_bound: 0
  upper_bound: 1
